replicaCount: 2
image:
  repository: 250139002704.dkr.ecr.us-east-1.amazonaws.com/todolist-server
  tag: af040784e135c10483aab33f938c04b5038af64e
  pullPolicy: IfNotPresent
service:
  enabled: true
  name: todo-server
  type: LoadBalancer
  port: 8080
  targetPort: 8080
  annotations: {}
resources: {}
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: true
  minAvailable: 1
secrets:
  awsRegion: "us-east-1" # Placeholder, replace with your AWS region
  awsSecretName: "todolist-db-credentials"
  dbPassword: "changeme" # Placeholder, replace with real password
  jwtSecret: "changeme" # Placeholder, replace with real secret
