apiVersion: v1
replicaCount: 2

image:
  repository: 250139002704.dkr.ecr.us-east-1.amazonaws.com/todolist-client
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  name: todo-client
  type: LoadBalancer
  port: 80
  targetPort: 80
  annotations: {}

resources: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 1
