apiVersion: v1
replicaCount: 2
image:
  repository: 250139002704.dkr.ecr.us-east-1.amazonaws.com/todolist-client
  tag: af040784e135c10483aab33f938c04b5038af64e
  pullPolicy: IfNotPresent
service:
  enabled: true
  name: todo-client
  type: LoadBalancer
  port: 3000
  targetPort: 3000
  annotations: {}
resources: {}
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: true
  minAvailable: 1
