apiVersion: v1
replicaCount: 2
image:
  repository: 250139002704.dkr.ecr.us-east-1.amazonaws.com/todolist-client
  tag: 3829dc72aa6e606f72476754e5dbacfacd0e5083
  pullPolicy: IfNotPresent
service:
  enabled: true
  name: todo-client
  type: LoadBalancer
  port: 3000
  targetPort: 3000
  annotations: {}
resources: {}
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
podDisruptionBudget:
  enabled: true
  minAvailable: 1
