apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  labels:
    app: {{ include "server.name" . }}
    chart: {{ include "server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "server.name" . }}
    release: {{ .Release.Name }}