apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "client.fullname" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ include "client.name" . }}
      release: {{ .Release.Name }}