name: Build and Push Multi-Arch Docker Images to ECR

on:
  push:
    branches:
      - stage
      - main

permissions:
  contents: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  CLIENT_REPO: todolist-client
  SERVER_REPO: todolist-server
  REACT_APP_API_BASE_URL: http://a7989b15a8d55467fa3105bcf5da698b-555298074.us-east-1.elb.amazonaws.com:8080

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug environment variables
        run: |
          echo "ACCOUNT_ID: $ACCOUNT_ID"
          echo "AWS_REGION: $AWS_REGION"
          echo "CLIENT_REPO: $CLIENT_REPO"
          echo "SERVER_REPO: $SERVER_REPO"
          echo "REACT_APP_API_BASE_URL: $REACT_APP_API_BASE_URL"

      # Build and push client image
      - name: Build and push multi-arch client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REACT_APP_API_BASE_URL=${{ env.REACT_APP_API_BASE_URL }}
          tags: |
            ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.CLIENT_REPO }}:latest
            ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.CLIENT_REPO }}:${{ github.sha }}

      # Build and push server image
      - name: Build and push multi-arch server image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.SERVER_REPO }}:latest
            ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.SERVER_REPO }}:${{ github.sha }}

      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update image tags in Helm values.yaml
        run: |
          yq -i ".image.tag = \"${GITHUB_SHA}\"" helm-charts/server/values.yaml
          yq -i ".image.tag = \"${GITHUB_SHA}\"" helm-charts/client/values.yaml

      - name: Commit and push updated image tags
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add helm-charts/server/values.yaml helm-charts/client/values.yaml
          git commit -m "chore: update image tags to $GITHUB_SHA [skip ci]" || echo "No changes to commit"
          git push
